name: Monitoring

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run monitoring script
        uses: actions/checkout@v4
      - run: |
          bash monitoring.sh
      - name: Update Disciplines
        run: |
          bash updateDisciplines.sh
          bash updateCountries.sh
          git config user.name Github Action
          git config user.email actions@github.com
          git add src/disciplines.json
          git add src/countries.json
          timestamp=$(date -u)
          git commit -m "update disciplines: ${timestamp}" || exit 0
          git push